[window]
title = "Sherion"

[font]
family = "DejaVu Sans Mono"
size = 14.0
fallback = [
    "Symbols Nerd Font Mono",
    "Symbols Nerd Font",
    "JetBrainsMono Nerd Font Mono",
    "MesloLGS Nerd Font",
    "Noto Sans Symbols",
    "Noto Color Emoji",
]

[colors]
foreground = "#cccccc"
background = "#1e1e1e"
cursor = "#ffffff"

[terminal]
scrollback_lines = 10000
shell = ""

[bell]
visual = true

[appearance]
theme = "auto"
opacity = 1.0

[ui]
font_zoom = 1.0
sidebar_width = 157.1796875
sidebar_collapsed = false
view_mode = "single"

[session]
restore_tabs = false
cwd = ["/home/anilo/Projeler/sherion"]
